In [7]:
#QUESTION 1
import numpy as np
def func(array):
    print("MIN IN THE ARRAY IS :",array.min())
    print("MAX IN THE ARRAY IS:",array.max())
    print("AVERAGE OF THE ARRAY IS:",array.mean())
    count=0
    for i in array[11]:
        if(i%2==0):
            count+=1
    print("NO. OF EVENS IN THE LAST ROW IS:",count)
arr=np.random.randint(1,100,60)
arr1=arr.reshape(12,5)
print("ARRAY:")
print(arr1)
func(arr1)


ARRAY:
[[36 62 20 31 33]
 [ 7 78 11 35 72]
 [23 91  2 13  7]
 [99 72 46 24 28]
 [83  2  2 38 62]
 [53 75  8 47 51]
 [80 83  1 46 65]
 [92 31 97 16 27]
 [69 82 11 84 11]
 [15 42 35 40 61]
 [24  5 51 29 19]
 [ 9  8 63 98 50]]
MIN IN THE ARRAY IS : 1
MAX IN THE ARRAY IS: 99
AVERAGE OF THE ARRAY IS: 42.583333333333336
NO. OF EVENS IN THE LAST ROW IS: 3


In [15]:
#QUESTION 2
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
print("after slicing")
print(array1[0:,-1::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
after slicing
[[3 2 1]
 [6 5 4]
 [9 8 7]]
