In [25]:
#QUESTION 1
import numpy as np
print("BEFORE:")
arr=np.random.randint(1,100,60)
array=arr.reshape(12,5)
print(array)
lst=[-5,-4,-3,-2,-1]
j=1
for i in lst:
    arr[i]=j
    j+=1
print("AFTER:")
print(arr.reshape(12,5))

BEFORE:
[[30 83 82  3 27]
 [21  9  4 83 65]
 [38 52 32 49 11]
 [80 66  7 26 70]
 [85 28  9 46 89]
 [66 99  8 79 54]
 [44 42 89 30 41]
 [87 63 89 87 24]
 [87 90 32 16 63]
 [40 54 15 42 64]
 [30 36 51 69 72]
 [26 41 64 43 21]]
AFTER:
[[30 83 82  3 27]
 [21  9  4 83 65]
 [38 52 32 49 11]
 [80 66  7 26 70]
 [85 28  9 46 89]
 [66 99  8 79 54]
 [44 42 89 30 41]
 [87 63 89 87 24]
 [87 90 32 16 63]
 [40 54 15 42 64]
 [30 36 51 69 72]
 [ 1  2  3  4  5]]


In [23]:
# QUESTION 2
import numpy as np
arr=np.random.randint(1,100,60)
array=arr.reshape(12,5)
print(array)
i=0
for row in array:
    print("max in row",i,"is:",max(row))
    print("min in row",i,"is:",min(row))

[[18 10 33 14  2]
 [29 73 49 32 22]
 [68 64 12 69 66]
 [80 34 54 15 34]
 [18 81 71  8 67]
 [89 53 33 67 26]
 [22 20 57 11 97]
 [98 64 46 44 45]
 [80 24 12 39 55]
 [47 29 31 32 62]
 [47 42  3 45  6]
 [90 69 45 99 15]]
max in row 0 is: 33
min in row 0 is: 2
max in row 0 is: 73
min in row 0 is: 22
max in row 0 is: 69
min in row 0 is: 12
max in row 0 is: 80
min in row 0 is: 15
max in row 0 is: 81
min in row 0 is: 8
max in row 0 is: 89
min in row 0 is: 26
max in row 0 is: 97
min in row 0 is: 11
max in row 0 is: 98
min in row 0 is: 44
max in row 0 is: 80
min in row 0 is: 12
max in row 0 is: 62
min in row 0 is: 29
max in row 0 is: 47
min in row 0 is: 3
max in row 0 is: 99
min in row 0 is: 15
